In [ ]:
import torch

In [ ]:
t = torch.FloatTensor([0., 1., 2., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 4., 5., 6.])


In [ ]:
print(t[0], t[1], t[-1])
print(2*t)

tensor(0.) tensor(1.) tensor(6.)
tensor([ 0.,  2.,  4.,  8., 10., 12.])


In [ ]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                       ])

In [ ]:
print(t[:, 1])
print(t[:, 1].size())

print(t[:, :-1])

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [ ]:
# 브로드캐스트 기능 (맞춰주는 기능)
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3]])

print(m1 + m2)

m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])

print(m1 + m2)

tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

print(m1.matmul(m2))
print(m1 @ m2)
print("--------------------")
print(m1.mul(m2))
print(m1 * m2)

tensor([[ 5.],
        [11.]])
tensor([[ 5.],
        [11.]])
--------------------
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())      # 전체 값 평균
print(t.mean(dim=0))    # 열 기준으로 평균 계산 (1차원 제거)

tensor(2.5000)
tensor([2., 3.])


In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.sum())
print(t.sum(dim=0))

tensor(10.)
tensor([4., 6.])


In [ ]:
print(t.max(dim=0))   # 뒤에는 인덱스 정보

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [ ]:
import numpy as np

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [ ]:
print(ft.view([4, 3]))

print(ft.view([4, 1, 3]))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])


In [ ]:
# squeeze
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)

print(ft.squeeze())

ft = torch.FloatTensor([[[0]], [[1]], [[2]]])
print(ft.squeeze())

tensor([[0.],
        [1.],
        [2.]])
tensor([0., 1., 2.])
tensor([0., 1., 2.])


In [ ]:
# unsqueeze
ft = torch.Tensor([0, 1, 2])
print(ft.shape)
print(ft.unsqueeze(0))
print(ft.unsqueeze(1))

torch.Size([3])
tensor([[0., 1., 2.]])
tensor([[0.],
        [1.],
        [2.]])


<h1>2번째 pytorch</h1>

In [1]:
import torch

t = torch.FloatTensor([1, 1])
t.float()

tensor([1., 1.])

In [3]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [4]:
torch.cat([x,y], dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [5]:
torch.cat([x,y], dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [6]:
torch.stack([x, y])

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [11]:
x = torch.FloatTensor([[1, 2], [3, 4], [5, 6]])
x

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [8]:
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.]])

<h1>직접 선형회귀 구현하기</h1>

In [20]:
import torch

# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = torch.optim.SGD([W, b], lr=0.01)

nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

In [22]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [4], [9]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = torch.optim.SGD([W, b], lr=0.01)

nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train ** W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.072, b: 0.073 Cost: 24.333334
Epoch  100/1999 W: 1.955, b: 0.358 Cost: 0.064149
Epoch  200/1999 W: 1.983, b: 0.135 Cost: 0.009166
Epoch  300/1999 W: 1.994, b: 0.051 Cost: 0.001302
Epoch  400/1999 W: 1.998, b: 0.019 Cost: 0.000185
Epoch  500/1999 W: 1.999, b: 0.007 Cost: 0.000026
Epoch  600/1999 W: 2.000, b: 0.003 Cost: 0.000004
Epoch  700/1999 W: 2.000, b: 0.001 Cost: 0.000001
Epoch  800/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch  900/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1000/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1100/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1200/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1300/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1400/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1500/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1600/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1700/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1800/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1900/1999 W: 2.000, b: 0.000 Cost: 0.000000

In [24]:
import torch

w = torch.tensor(2.0, requires_grad=True)

y = w**2
z = 2*y + 5

z.backward()

print(w.grad)

tensor(8.)


In [46]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

# 훈련 데이터
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [80], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 가중치 w와 편향 b 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/10000 w1: 0.294 w2: 0.294 w3: 0.290 b: 0.003 Cost: 29661.800781
Epoch  100/10000 w1: 0.688 w2: 0.681 w3: 0.658 b: 0.008 Cost: 5.754573
Epoch  200/10000 w1: 0.697 w2: 0.684 w3: 0.645 b: 0.008 Cost: 5.512386
Epoch  300/10000 w1: 0.707 w2: 0.686 w3: 0.634 b: 0.008 Cost: 5.281667
Epoch  400/10000 w1: 0.715 w2: 0.689 w3: 0.622 b: 0.008 Cost: 5.061868
Epoch  500/10000 w1: 0.724 w2: 0.691 w3: 0.611 b: 0.008 Cost: 4.852424
Epoch  600/10000 w1: 0.733 w2: 0.693 w3: 0.600 b: 0.008 Cost: 4.652705
Epoch  700/10000 w1: 0.741 w2: 0.695 w3: 0.589 b: 0.009 Cost: 4.462287
Epoch  800/10000 w1: 0.750 w2: 0.697 w3: 0.579 b: 0.009 Cost: 4.280604
Epoch  900/10000 w1: 0.758 w2: 0.699 w3: 0.569 b: 0.009 Cost: 4.107294
Epoch 1000/10000 w1: 0.766 w2: 0.700 w3: 0.559 b: 0.009 Cost: 3.941866
Epoch 1100/10000 w1: 0.774 w2: 0.702 w3: 0.549 b: 0.009 Cost: 3.783911
Epoch 1200/10000 w1: 0.782 w2: 0.703 w3: 0.540 b: 0.009 Cost: 3.633077
Epoch 1300/10000 w1: 0.790 w2: 0.704 w3: 0.531 b: 0.009 Cost: 3.488997
Ep

In [48]:
torch.manual_seed(1)

x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  80],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
      print('Epoch {:4d}/{} W: {} Cost: {:.6f}'.format(
          epoch, nb_epochs, W.squeeze().detach(), cost.item()
      ))

Epoch    0/1000 W: tensor([0.2940, 0.2936, 0.2902]) Cost: 29661.800781
Epoch  100/1000 W: tensor([0.6882, 0.6809, 0.6577]) Cost: 5.754573
Epoch  200/1000 W: tensor([0.6974, 0.6837, 0.6455]) Cost: 5.512386
Epoch  300/1000 W: tensor([0.7065, 0.6863, 0.6336]) Cost: 5.281667
Epoch  400/1000 W: tensor([0.7155, 0.6888, 0.6221]) Cost: 5.061907
Epoch  500/1000 W: tensor([0.7243, 0.6911, 0.6108]) Cost: 4.852424
Epoch  600/1000 W: tensor([0.7330, 0.6932, 0.5999]) Cost: 4.652731
Epoch  700/1000 W: tensor([0.7415, 0.6952, 0.5892]) Cost: 4.462265
Epoch  800/1000 W: tensor([0.7499, 0.6971, 0.5788]) Cost: 4.280604
Epoch  900/1000 W: tensor([0.7581, 0.6988, 0.5687]) Cost: 4.107261
Epoch 1000/1000 W: tensor([0.7663, 0.7004, 0.5589]) Cost: 3.941853
